# Generated by Django 5.1.6 on 2025-03-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='organization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('END_USER', 'End User'), ('AI_ENGINEER', 'AI Engineer'), ('ADMIN', 'Admin'), ('FINANCE', 'Finance')], default='END_USER', max_length=20),
            preserve_default=False,
        ),
    ]
