services:
  mysql:
    image: mysql:latest
    container_name: insurance_mlaas_mysql
    environment:
      MYSQL_DATABASE: insurance_mlaas
      MYSQL_USER: mlaas_user
      MYSQL_PASSWORD: SecurePass123
      MYSQL_ROOT_PASSWORD: MyNewPass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - "C:/Users/alexh/OneDrive - UWE Bristol/Documents/MLAAS_DESD/insurance_mlaas.sql:/docker-entrypoint-initdb.d/insurance_mlaas.sql"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: desd_backend
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_NAME: insurance_mlaas
      DB_USER: mlaas_user
      DB_PASSWORD: SecurePass123
      DB_HOST: mysql
      DB_PORT: 3306
    volumes:
      - ./backend:/app

  ml_model:
    build: ./ml_model
    container_name: ml_model
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - backend
    volumes:
      - ./ml_model:/app

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: MyNewPass

volumes:
  mysql_data: